import type { ExplorerBlueprintData } from '../types';

export const PATTERN_BLUEPRINTS: Record<string, ExplorerBlueprintData> = {
  residual: {
    patternId: 'residual',
    title: 'Residual Skip Connection Schema',
    description: 'Gradient superhighway shortcut adding input x directly to non-linear residual mapping F(x).',
    viewBox: '0 0 520 160',
    nodes: [
      {
        id: 'node-input',
        label: 'Input Tensor (x)',
        sublabel: '[B, C, H, W]',
        type: 'input',
        role: 'Input Feature Activations',
        purpose: 'Provides original input tensor activations directly to both weight block and skip path.',
        informationFlow: 'Splits simultaneously into identity shortcut and residual weight transformation path.',
        educationalNotes: [
          'Preserves raw feature representation across deep network layers.',
          'Enables unimpeded backward gradient flow during backpropagation.',
        ],
        relatedConcepts: ['Gradient Superhighway', 'Identity Mapping', 'Vanishing Gradient Mitigation'],
        x: 60,
        y: 75,
        width: 105,
        height: 42,
        shape: 'pill',
        strokeColor: '#94a3b8',
        fillColor: '#0f172a',
        textColor: '#94a3b8',
        badge: 'Input',
      },
      {
        id: 'node-weight-block',
        label: 'Weight Block F(x)',
        sublabel: '2x Conv 3x3 + BN + ReLU',
        type: 'weight-block',
        role: 'Residual Transformation Function',
        purpose: 'Learns non-linear residual perturbation F(x) = H(x) - x rather than unconstrained mapping H(x).',
        informationFlow: 'Processes input activations through spatial convolution, normalization, and non-linearity.',
        educationalNotes: [
          'If identity is optimal, weights can easily decay to zero (F(x) = 0).',
          'Avoids degradation problem when network depth scales beyond 100 layers.',
        ],
        relatedConcepts: ['Non-linear Mapping', 'Convolutional Layer', 'Batch Normalization'],
        x: 220,
        y: 75,
        width: 125,
        height: 46,
        shape: 'rect',
        strokeColor: '#3b82f6',
        fillColor: '#0f172a',
        textColor: '#3b82f6',
        badge: 'Transform',
      },
      {
        id: 'node-add',
        label: '+',
        sublabel: 'Element Sum',
        type: 'operation',
        role: 'Identity Addition Junction',
        purpose: 'Combines residual transformed features F(x) with untouched identity shortcut x.',
        informationFlow: 'Executes element-wise addition: H(x) = F(x) + x.',
        educationalNotes: [
          'Requires matching spatial dimensions and channel counts between F(x) and x.',
          'Provides identity derivative d(F(x)+x)/dx = dF/dx + 1 ensuring non-zero gradient.',
        ],
        relatedConcepts: ['Element-wise Addition', 'Shortcut Connection', 'Gradient Conservation'],
        x: 385,
        y: 75,
        width: 32,
        height: 32,
        shape: 'circle',
        strokeColor: '#10b981',
        fillColor: '#0f172a',
        textColor: '#10b981',
        badge: 'Add',
      },
      {
        id: 'node-output',
        label: 'Output F(x) + x',
        sublabel: 'To ReLU / Next Layer',
        type: 'output',
        role: 'Residual Block Output',
        purpose: 'Delivers combined activations H(x) = F(x) + x to subsequent network layers.',
        informationFlow: 'Feeds next residual block or downsampling transition layer.',
        educationalNotes: [
          'Allows signal to pass cleanly through hundreds of sequential blocks.',
        ],
        relatedConcepts: ['Feature Propagation', 'ResNet Architecture'],
        x: 470,
        y: 75,
        width: 85,
        height: 42,
        shape: 'pill',
        strokeColor: '#10b981',
        fillColor: '#0f172a',
        textColor: '#10b981',
        badge: 'Output',
      },
    ],
    edges: [
      {
        id: 'edge-in-weight',
        source: 'node-input',
        target: 'node-weight-block',
        label: 'x',
        type: 'sequential',
        color: '#64748b',
      },
      {
        id: 'edge-weight-add',
        source: 'node-weight-block',
        target: 'node-add',
        label: 'F(x)',
        type: 'sequential',
        color: '#3b82f6',
      },
      {
        id: 'edge-identity-skip',
        source: 'node-input',
        target: 'node-add',
        label: 'Identity Skip Path (x)',
        type: 'skip',
        color: '#10b981',
        dashed: true,
        pathD: 'M 60,54 C 140,12 305,12 385,57',
      },
      {
        id: 'edge-add-out',
        source: 'node-add',
        target: 'node-output',
        label: 'F(x) + x',
        type: 'sequential',
        color: '#10b981',
      },
    ],
  },

  dense: {
    patternId: 'dense',
    title: 'Dense Concatenation Highway Schema',
    description: 'Direct channel concatenation linking every layer to all subsequent layers in a dense block.',
    viewBox: '0 0 520 160',
    nodes: [
      {
        id: 'node-layer-0',
        label: 'Layer 0 (x0)',
        sublabel: 'Input Features [k0]',
        type: 'layer',
        role: 'Dense Block Input Layer',
        purpose: 'Provides initial feature maps x0 into the dense block.',
        informationFlow: 'Concatenated into inputs of Layer 1, Layer 2, and block output.',
        educationalNotes: ['Maximizes feature reuse across entire block.', 'Reduces parameter count by keeping growth rate k small.'],
        relatedConcepts: ['Feature Reuse', 'DenseNet', 'Growth Rate'],
        x: 55,
        y: 75,
        width: 85,
        height: 44,
        shape: 'rect',
        strokeColor: '#3b82f6',
        fillColor: '#0f172a',
        textColor: '#3b82f6',
        badge: 'Layer 0',
      },
      {
        id: 'node-layer-1',
        label: 'Layer 1 (x1)',
        sublabel: 'H1([x0])',
        type: 'layer',
        role: 'First Dense Layer',
        purpose: 'Computes feature map x1 from x0 and concatenates both for subsequent layers.',
        informationFlow: 'Receives x0; passes [x0, x1] downstream.',
        educationalNotes: ['Direct connection ensures zero gradient decay.'],
        relatedConcepts: ['Channel Concatenation', 'Feature Aggregation'],
        x: 190,
        y: 75,
        width: 85,
        height: 44,
        shape: 'rect',
        strokeColor: '#3b82f6',
        fillColor: '#0f172a',
        textColor: '#3b82f6',
        badge: 'Layer 1',
      },
      {
        id: 'node-layer-2',
        label: 'Layer 2 (x2)',
        sublabel: 'H2([x0, x1])',
        type: 'layer',
        role: 'Second Dense Layer',
        purpose: 'Processes concatenated features [x0, x1] to generate new feature channels x2.',
        informationFlow: 'Receives concatenated x0 and x1; outputs [x0, x1, x2].',
        educationalNotes: ['Combines low-level features with higher-level representations.'],
        relatedConcepts: ['Multi-scale Representation', 'Collective Knowledge'],
        x: 325,
        y: 75,
        width: 85,
        height: 44,
        shape: 'rect',
        strokeColor: '#3b82f6',
        fillColor: '#0f172a',
        textColor: '#3b82f6',
        badge: 'Layer 2',
      },
      {
        id: 'node-output',
        label: 'Concat Output',
        sublabel: '[x0, x1, x2]',
        type: 'output',
        role: 'Dense Block Output',
        purpose: 'Aggregates all accumulated feature maps into transition downsampling layer.',
        informationFlow: 'Feeds 1x1 Conv + 2x2 AvgPool transition layer.',
        educationalNotes: ['Transition layers compress channel dimension before pooling.'],
        relatedConcepts: ['Transition Layer', 'Channel Compression'],
        x: 460,
        y: 75,
        width: 95,
        height: 44,
        shape: 'pill',
        strokeColor: '#8b5cf6',
        fillColor: '#0f172a',
        textColor: '#8b5cf6',
        badge: 'Output',
      },
    ],
    edges: [
      { id: 'edge-0-1', source: 'node-layer-0', target: 'node-layer-1', type: 'sequential', color: '#64748b' },
      { id: 'edge-1-2', source: 'node-layer-1', target: 'node-layer-2', type: 'sequential', color: '#64748b' },
      { id: 'edge-2-out', source: 'node-layer-2', target: 'node-output', type: 'sequential', color: '#64748b' },
      {
        id: 'edge-dense-0-2',
        source: 'node-layer-0',
        target: 'node-layer-2',
        label: 'Dense Link (x0 -> Layer 2)',
        type: 'concatenation',
        color: '#8b5cf6',
        dashed: true,
        pathD: 'M 55,53 C 120,12 260,12 325,53',
      },
      {
        id: 'edge-dense-0-out',
        source: 'node-layer-0',
        target: 'node-output',
        label: 'Highway (x0 -> Output)',
        type: 'concatenation',
        color: '#8b5cf6',
        dashed: true,
        pathD: 'M 55,97 C 160,148 355,148 460,97',
      },
    ],
  },

  depthwise: {
    patternId: 'depthwise',
    title: 'Depthwise Separable Convolution Schema',
    description: 'Factorized convolution splitting spatial filtering from channel mixing to reduce computation by 8-9x.',
    viewBox: '0 0 520 160',
    nodes: [
      {
        id: 'node-input',
        label: 'Input Tensor',
        sublabel: '[B, C_in, H, W]',
        type: 'input',
        role: 'Input Feature Maps',
        purpose: 'Receives feature maps with C_in channels.',
        informationFlow: 'Passes individual channels separately into spatial depthwise filters.',
        educationalNotes: ['Standard conv computes spatial and channel filtering simultaneously.'],
        relatedConcepts: ['MobileNet', 'Factorized Convolution'],
        x: 55,
        y: 75,
        width: 95,
        height: 42,
        shape: 'pill',
        strokeColor: '#94a3b8',
        fillColor: '#0f172a',
        textColor: '#94a3b8',
        badge: 'Input',
      },
      {
        id: 'node-dw-conv',
        label: 'Depthwise Conv',
        sublabel: 'Spatial Only (K×K)',
        type: 'operation',
        role: 'Per-Channel Spatial Filtering',
        purpose: 'Applies a single 3x3 filter per input channel without mixing across channels.',
        informationFlow: 'Filters spatial dimensions per channel independently.',
        educationalNotes: ['Computes spatial features with 1/C cost of standard conv.'],
        relatedConcepts: ['Spatial Kernel', 'Grouped Convolution'],
        x: 195,
        y: 75,
        width: 120,
        height: 48,
        shape: 'rect',
        strokeColor: '#06b6d4',
        fillColor: '#0f172a',
        textColor: '#06b6d4',
        badge: 'Spatial',
      },
      {
        id: 'node-pw-conv',
        label: 'Pointwise Conv',
        sublabel: 'Channel Mixing (1×1)',
        type: 'operation',
        role: 'Cross-Channel Linear Combination',
        purpose: 'Applies 1x1 convolutions across all spatial channels to combine features into C_out maps.',
        informationFlow: 'Linearly combines spatial features across channels.',
        educationalNotes: ['Computes channel combinations efficiently.'],
        relatedConcepts: ['1x1 Convolution', 'Channel Fusion'],
        x: 345,
        y: 75,
        width: 120,
        height: 48,
        shape: 'rect',
        strokeColor: '#3b82f6',
        fillColor: '#0f172a',
        textColor: '#3b82f6',
        badge: 'Channel',
      },
      {
        id: 'node-output',
        label: 'Output Tensor',
        sublabel: '[B, C_out, H, W]',
        type: 'output',
        role: 'Separable Output',
        purpose: 'Delivers factorized feature maps with reduced computational cost.',
        informationFlow: 'Passed to subsequent separable or bottleneck blocks.',
        educationalNotes: ['Saves ~8x to 9x FLOPs compared to standard 3x3 convolution.'],
        relatedConcepts: ['Efficiency', 'FLOP Reduction'],
        x: 465,
        y: 75,
        width: 85,
        height: 42,
        shape: 'pill',
        strokeColor: '#10b981',
        fillColor: '#0f172a',
        textColor: '#10b981',
        badge: 'Output',
      },
    ],
    edges: [
      { id: 'edge-in-dw', source: 'node-input', target: 'node-dw-conv', type: 'sequential', color: '#64748b' },
      { id: 'edge-dw-pw', source: 'node-dw-conv', target: 'node-pw-conv', label: 'Spatial Maps', type: 'sequential', color: '#06b6d4' },
      { id: 'edge-pw-out', source: 'node-pw-conv', target: 'node-output', type: 'sequential', color: '#3b82f6' },
    ],
  },

  compound: {
    patternId: 'compound',
    title: 'Compound Model Scaling Schema',
    description: 'Principled joint scaling of network depth (d), width (w), and resolution (r) using a fixed compound coefficient.',
    viewBox: '0 0 520 160',
    nodes: [
      {
        id: 'node-b0-base',
        label: 'Baseline B0 Model',
        sublabel: 'w=1.0, d=1.0, r=1.0',
        type: 'input',
        role: 'Baseline Architecture Anchor',
        purpose: 'Establishes initial baseline architecture discovered via grid search.',
        informationFlow: 'Serves as foundational reference for compound scaling coefficients.',
        educationalNotes: ['Single-dimension scaling yields diminishing accuracy returns.'],
        relatedConcepts: ['EfficientNet', 'Grid Search'],
        x: 65,
        y: 75,
        width: 105,
        height: 46,
        shape: 'rect',
        strokeColor: '#475569',
        fillColor: '#0f172a',
        textColor: '#94a3b8',
        badge: 'Baseline',
      },
      {
        id: 'node-width-scale',
        label: 'Width Scaling (w)',
        sublabel: 'Channels w = β^φ',
        type: 'component',
        role: 'Channel Dimension Expansion',
        purpose: 'Scales number of feature channels to capture fine-grained granular features.',
        informationFlow: 'Expands feature channel capacity per layer.',
        educationalNotes: ['Extremely wide thin models struggle to capture complex high-level abstractions.'],
        relatedConcepts: ['Channel Capacity', 'Granular Features'],
        x: 225,
        y: 40,
        width: 115,
        height: 40,
        shape: 'rect',
        strokeColor: '#f97316',
        fillColor: '#0f172a',
        textColor: '#f97316',
        badge: 'Width',
      },
      {
        id: 'node-depth-scale',
        label: 'Depth Scaling (d)',
        sublabel: 'Layers d = α^φ',
        type: 'component',
        role: 'Layer Count Expansion',
        purpose: 'Scales total layer count to capture richer, more complex feature hierarchies.',
        informationFlow: 'Increases sequential processing depth.',
        educationalNotes: ['Deep narrow models suffer from vanishing gradients and training difficulty.'],
        relatedConcepts: ['Receptive Field', 'Feature Hierarchy'],
        x: 225,
        y: 110,
        width: 115,
        height: 40,
        shape: 'rect',
        strokeColor: '#f97316',
        fillColor: '#0f172a',
        textColor: '#f97316',
        badge: 'Depth',
      },
      {
        id: 'node-compound-model',
        label: 'Compound Scaled B1-B7',
        sublabel: 'Balanced w, d, r Joint Scaling',
        type: 'output',
        role: 'Balanced Scaled Architecture',
        purpose: 'Jointly scales depth, width, and resolution using compound coefficient φ.',
        informationFlow: 'Achieves optimal Pareto frontier between accuracy and FLOPs.',
        educationalNotes: ['Achieves state-of-the-art accuracy with up to 10x fewer parameters.'],
        relatedConcepts: ['Pareto Efficiency', 'Compound Coefficient'],
        x: 420,
        y: 75,
        width: 135,
        height: 52,
        shape: 'rect',
        strokeColor: '#10b981',
        fillColor: '#0f172a',
        textColor: '#10b981',
        badge: 'Compound',
      },
    ],
    edges: [
      { id: 'edge-b0-w', source: 'node-b0-base', target: 'node-width-scale', type: 'sequential', color: '#f97316' },
      { id: 'edge-b0-d', source: 'node-b0-base', target: 'node-depth-scale', type: 'sequential', color: '#f97316' },
      { id: 'edge-w-compound', source: 'node-width-scale', target: 'node-compound-model', type: 'sequential', color: '#10b981' },
      { id: 'edge-d-compound', source: 'node-depth-scale', target: 'node-compound-model', type: 'sequential', color: '#10b981' },
    ],
  },

  nas: {
    patternId: 'nas',
    title: 'Neural Architecture Search (NAS) Loop Schema',
    description: 'Reinforcement learning feedback loop where an RNN controller generates cell architectures evaluated by a child network.',
    viewBox: '0 0 520 160',
    nodes: [
      {
        id: 'node-controller',
        label: 'Controller RNN',
        sublabel: 'Policy θ (LSTM/RL)',
        type: 'controller',
        role: 'Architecture Generator Controller',
        purpose: 'Generates candidate neural network architectural strings (layer types, kernel sizes, skip links).',
        informationFlow: 'Outputs architecture specification sequence to child network evaluator.',
        educationalNotes: ['Trained via Policy Gradient (REINFORCE) to maximize child validation accuracy.'],
        relatedConcepts: ['Reinforcement Learning', 'Policy Gradient', 'NASNet'],
        x: 90,
        y: 75,
        width: 125,
        height: 48,
        shape: 'rect',
        strokeColor: '#00d9ff',
        fillColor: '#0f172a',
        textColor: '#00d9ff',
        badge: 'Controller',
      },
      {
        id: 'node-child-net',
        label: 'Child Network',
        sublabel: 'Train & Evaluate',
        type: 'operation',
        role: 'Architecture Evaluator',
        purpose: 'Instantiates sampled cell architecture, trains on target dataset, and measures validation accuracy.',
        informationFlow: 'Computes validation accuracy R on unseen evaluation set.',
        educationalNotes: ['Training child models to convergence requires massive compute (hundreds of GPU hours).'],
        relatedConcepts: ['Child Model', 'Proxy Task Evaluation'],
        x: 345,
        y: 75,
        width: 125,
        height: 48,
        shape: 'rect',
        strokeColor: '#3b82f6',
        fillColor: '#0f172a',
        textColor: '#3b82f6',
        badge: 'Evaluator',
      },
      {
        id: 'node-reward',
        label: 'Reward Signal (R)',
        sublabel: 'Validation Accuracy',
        type: 'output',
        role: 'Reinforcement Learning Reward',
        purpose: 'Feeds scalar performance metric back to update controller policy parameters θ.',
        informationFlow: 'Provides reinforcement reward gradient to update controller RNN policy.',
        educationalNotes: ['Higher reward increases sampling probability of superior architectural motifs.'],
        relatedConcepts: ['Validation Accuracy', 'Policy Update'],
        x: 215,
        y: 125,
        width: 120,
        height: 28,
        shape: 'pill',
        strokeColor: '#10b981',
        fillColor: '#0f172a',
        textColor: '#10b981',
        badge: 'Reward',
      },
    ],
    edges: [
      {
        id: 'edge-sample-arch',
        source: 'node-controller',
        target: 'node-child-net',
        label: 'Samples Cell Arch',
        type: 'sequential',
        color: '#00d9ff',
        pathD: 'M 90,51 C 150,18 285,18 345,51',
      },
      {
        id: 'edge-feedback-reward',
        source: 'node-child-net',
        target: 'node-controller',
        label: 'Reward R (Val Acc)',
        type: 'feedback',
        color: '#10b981',
        dashed: true,
        pathD: 'M 345,99 C 285,138 150,138 90,99',
      },
    ],
  },

  attention: {
    patternId: 'attention',
    title: 'Self-Attention Mechanism Schema',
    description: 'Scaled dot-product attention mapping Queries (Q), Keys (K), and Values (V) to dynamic context vectors.',
    viewBox: '0 0 540 160',
    nodes: [
      {
        id: 'node-tokens',
        label: 'Tokens X',
        sublabel: '[Seq, d_model]',
        type: 'token',
        role: 'Input Sequence Embeddings',
        purpose: 'Provides input sequence vector representations.',
        informationFlow: 'Projected into Query (Q), Key (K), and Value (V) linear matrices.',
        educationalNotes: ['Self-attention models pairwise dependencies regardless of distance.'],
        relatedConcepts: ['Transformer', 'Sequence Embedding'],
        x: 45,
        y: 75,
        width: 70,
        height: 38,
        shape: 'pill',
        strokeColor: '#d946ef',
        fillColor: '#0f172a',
        textColor: '#d946ef',
        badge: 'Tokens',
      },
      {
        id: 'node-qkv',
        label: 'Projections Q, K, V',
        sublabel: 'Linear Layers',
        type: 'operation',
        role: 'Linear Projection Matrices',
        purpose: 'Projects tokens into specialized query, key, and value representation spaces.',
        informationFlow: 'Q and K feed similarity computation; V feeds output weighting.',
        educationalNotes: ['Multi-Head Attention uses multiple parallel Q, K, V projections.'],
        relatedConcepts: ['Linear Projection', 'Query-Key Matching'],
        x: 160,
        y: 75,
        width: 115,
        height: 48,
        shape: 'rect',
        strokeColor: '#a855f7',
        fillColor: '#0f172a',
        textColor: '#a855f7',
        badge: 'Q, K, V',
      },
      {
        id: 'node-similarity',
        label: 'Similarity (QK^T)',
        sublabel: 'Dot-Product / √d_k',
        type: 'operation',
        role: 'Pairwise Compatibility Scoring',
        purpose: 'Computes dot-product similarity scores between every query and key pair.',
        informationFlow: 'Feeds raw unnormalized alignment scores into Softmax activation.',
        educationalNotes: ['Divided by √d_k to prevent vanishing gradients at large dimensions.'],
        relatedConcepts: ['Dot-Product Attention', 'Scaling Factor'],
        x: 300,
        y: 45,
        width: 105,
        height: 38,
        shape: 'rect',
        strokeColor: '#a855f7',
        fillColor: '#0f172a',
        textColor: '#a855f7',
        badge: 'Scores',
      },
      {
        id: 'node-softmax',
        label: 'Softmax Weights',
        sublabel: 'Probabilities',
        type: 'operation',
        role: 'Attention Weight Normalization',
        purpose: 'Normalizes score matrix into positive probability distribution summing to 1.',
        informationFlow: 'Multiplies Value vectors V to compute weighted sum.',
        educationalNotes: ['Assigns dynamic attention weights based on context relevance.'],
        relatedConcepts: ['Attention Matrix', 'Softmax Activation'],
        x: 420,
        y: 45,
        width: 95,
        height: 34,
        shape: 'rect',
        strokeColor: '#d946ef',
        fillColor: '#0f172a',
        textColor: '#d946ef',
        badge: 'Softmax',
      },
      {
        id: 'node-output',
        label: 'Context Output',
        sublabel: 'Softmax(QK^T) V',
        type: 'output',
        role: 'Contextual Sequence Representation',
        purpose: 'Delivers dynamic context-aware representations for all sequence tokens.',
        informationFlow: 'Passed to feed-forward network (FFN) and residual layer norm.',
        educationalNotes: ['Captures long-range dependencies in O(1) sequential steps.'],
        relatedConcepts: ['Context Vector', 'Self-Attention Output'],
        x: 485,
        y: 105,
        width: 85,
        height: 38,
        shape: 'pill',
        strokeColor: '#10b981',
        fillColor: '#0f172a',
        textColor: '#10b981',
        badge: 'Context',
      },
    ],
    edges: [
      { id: 'edge-tok-qkv', source: 'node-tokens', target: 'node-qkv', type: 'sequential', color: '#d946ef' },
      { id: 'edge-qkv-sim', source: 'node-qkv', target: 'node-similarity', label: 'Q, K', type: 'projection', color: '#a855f7' },
      { id: 'edge-sim-soft', source: 'node-similarity', target: 'node-softmax', type: 'sequential', color: '#a855f7' },
      { id: 'edge-soft-out', source: 'node-softmax', target: 'node-output', label: 'Weights', type: 'sequential', color: '#d946ef' },
      {
        id: 'edge-val-out',
        source: 'node-qkv',
        target: 'node-output',
        label: 'Value Path (V)',
        type: 'projection',
        color: '#a855f7',
        dashed: true,
        pathD: 'M 160,99 C 240,135 380,135 485,124',
      },
    ],
  },
};
